/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PlanningRouteImport } from './routes/planning'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as TeamRouteImport } from './routes/team'
import { Route as AccountsNewRouteImport } from './routes/accounts_.new'
import { Route as ContactsNewRouteImport } from './routes/contacts_.new'
import { Route as LeadsNewRouteImport } from './routes/leads_.new'
import { Route as ResourcesNewRouteImport } from './routes/resources_.new'
import { Route as TeamNewRouteImport } from './routes/team_.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanningRoute = PlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsNewRoute = AccountsNewRouteImport.update({
  id: '/accounts_/new',
  path: '/accounts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsNewRoute = ContactsNewRouteImport.update({
  id: '/contacts_/new',
  path: '/contacts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsNewRoute = LeadsNewRouteImport.update({
  id: '/leads_/new',
  path: '/leads/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesNewRoute = ResourcesNewRouteImport.update({
  id: '/resources_/new',
  path: '/resources/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamNewRoute = TeamNewRouteImport.update({
  id: '/team_/new',
  path: '/team/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/contacts': typeof ContactsRoute
  '/leads': typeof LeadsRoute
  '/notifications': typeof NotificationsRoute
  '/planning': typeof PlanningRoute
  '/resources': typeof ResourcesRoute
  '/team': typeof TeamRoute
  '/accounts/new': typeof AccountsNewRoute
  '/contacts/new': typeof ContactsNewRoute
  '/leads/new': typeof LeadsNewRoute
  '/resources/new': typeof ResourcesNewRoute
  '/team/new': typeof TeamNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/contacts': typeof ContactsRoute
  '/leads': typeof LeadsRoute
  '/notifications': typeof NotificationsRoute
  '/planning': typeof PlanningRoute
  '/resources': typeof ResourcesRoute
  '/team': typeof TeamRoute
  '/accounts/new': typeof AccountsNewRoute
  '/contacts/new': typeof ContactsNewRoute
  '/leads/new': typeof LeadsNewRoute
  '/resources/new': typeof ResourcesNewRoute
  '/team/new': typeof TeamNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/contacts': typeof ContactsRoute
  '/leads': typeof LeadsRoute
  '/notifications': typeof NotificationsRoute
  '/planning': typeof PlanningRoute
  '/resources': typeof ResourcesRoute
  '/team': typeof TeamRoute
  '/accounts_/new': typeof AccountsNewRoute
  '/contacts_/new': typeof ContactsNewRoute
  '/leads_/new': typeof LeadsNewRoute
  '/resources_/new': typeof ResourcesNewRoute
  '/team_/new': typeof TeamNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/contacts'
    | '/leads'
    | '/notifications'
    | '/planning'
    | '/resources'
    | '/team'
    | '/accounts/new'
    | '/contacts/new'
    | '/leads/new'
    | '/resources/new'
    | '/team/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/contacts'
    | '/leads'
    | '/notifications'
    | '/planning'
    | '/resources'
    | '/team'
    | '/accounts/new'
    | '/contacts/new'
    | '/leads/new'
    | '/resources/new'
    | '/team/new'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/contacts'
    | '/leads'
    | '/notifications'
    | '/planning'
    | '/resources'
    | '/team'
    | '/accounts_/new'
    | '/contacts_/new'
    | '/leads_/new'
    | '/resources_/new'
    | '/team_/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  ContactsRoute: typeof ContactsRoute
  LeadsRoute: typeof LeadsRoute
  NotificationsRoute: typeof NotificationsRoute
  PlanningRoute: typeof PlanningRoute
  ResourcesRoute: typeof ResourcesRoute
  TeamRoute: typeof TeamRoute
  AccountsNewRoute: typeof AccountsNewRoute
  ContactsNewRoute: typeof ContactsNewRoute
  LeadsNewRoute: typeof LeadsNewRoute
  ResourcesNewRoute: typeof ResourcesNewRoute
  TeamNewRoute: typeof TeamNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planning': {
      id: '/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof PlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts_/new': {
      id: '/accounts_/new'
      path: '/accounts/new'
      fullPath: '/accounts/new'
      preLoaderRoute: typeof AccountsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts_/new': {
      id: '/contacts_/new'
      path: '/contacts/new'
      fullPath: '/contacts/new'
      preLoaderRoute: typeof ContactsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads_/new': {
      id: '/leads_/new'
      path: '/leads/new'
      fullPath: '/leads/new'
      preLoaderRoute: typeof LeadsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources_/new': {
      id: '/resources_/new'
      path: '/resources/new'
      fullPath: '/resources/new'
      preLoaderRoute: typeof ResourcesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team_/new': {
      id: '/team_/new'
      path: '/team/new'
      fullPath: '/team/new'
      preLoaderRoute: typeof TeamNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  ContactsRoute: ContactsRoute,
  LeadsRoute: LeadsRoute,
  NotificationsRoute: NotificationsRoute,
  PlanningRoute: PlanningRoute,
  ResourcesRoute: ResourcesRoute,
  TeamRoute: TeamRoute,
  AccountsNewRoute: AccountsNewRoute,
  ContactsNewRoute: ContactsNewRoute,
  LeadsNewRoute: LeadsNewRoute,
  ResourcesNewRoute: ResourcesNewRoute,
  TeamNewRoute: TeamNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
